# print('Now I need money')
# input()
# input('Give me a some money: ')
# money = input('Give me some money : ')
# print("here is your money ",money)
first_money = input('kodom Ali,Dosto kichu taka dey: ')
second_money = input('peyara begum,dosto kico taka dey : ')
print(type(first_money))
# by default the input from user will be string type:
first_money_int = int(first_money)
second_money_int = int(second_money)
print(first_money,second_money)
total = (first_money + second_money)
total1 = (first_money_int + second_money_int)
print(total1)
# print('total money i got: ',total)